name: deploy

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    paths: 
    - src/*
    paths-ignore:
    - README.md
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      uses: actions/steup-node@master
      with:
          node-version:'latest'
    - run: npm install
    - run: npm run build