name: deploy

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    paths-ignore:
    - README.md
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      uses: actions/setup-node@master
      with:
          node-version: 'latest'
    - run: npm install
    - run: npm run build

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3.0.1
      with:
        # Artifact name
        name: artifact
        # Path of the directory containing the static assets.
        path: dist
        # Duration after which artifact will expire in days.
        retention-days: 1
    # - name: Deploy GitHub Pages site
    #   uses: actions/deploy-pages@v4.0.5
    #   with:
    #     # GitHub token
    #     token: ${{ github.token }}
    #     # Time in milliseconds after which to timeout and cancel the deployment (default: 10 minutes)
    #     timeout: 600000
    #     # Maximum number of status report errors before cancelling a deployment (default: 10)
    #     error_count: 10
    #     # Time in milliseconds between two deployment status report (default: 5 seconds)
    #     reporting_interval: 10000
    #     # Name of the artifact to deploy
    #     artifact_name: artifact
          
