name: deploy

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    paths-ignore:
    - README.md
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      uses: actions/setup-node@master
      with:
          node-version: 'latest'
    - run: npm install
    - run: npm run build
    # - name: Deploy to GitHub Pages
    #   uses: actions/deploy-page
    #   # uses: peaceiris/actions-gh-pages@v3.9.3
    #   with:
    #     github_token: ${{ secrets.GITHUB_TOKEN }}
    #     publish_dir: ./dist  # 指向你的构建输出目录

    - name: Deploy
      # 使用别人写好的 actions去部署（将打包文件部署到指定分支上）
      uses: JamesIves/github-pages-deploy-action@v4.3.3
      # 自定义环境变量
      with:
        # 填写打包好的目录名称路径，本项目配置在根目录
        folder: dist