name: deploy

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    paths-ignore:
    - README.md
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      uses: actions/setup-node@master
      with:
          node-version: 'latest'
    - run: npm install
    - run: npm run build
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist  # 指向你的构建输出目录