name: deploy

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
    paths-ignore:
    - README.md
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build
      uses: actions/setup-node@master
      with:
          node-version: 'latest'
    - run: npm install
    - run: npm run build

    - name: Upload GitHub Pages artifact
      uses: actions/upload-pages-artifact@v3.0.1
      with:
        # Artifact name
        name: github-pages
        # Path of the directory containing the static assets.
        path: dist/
        # Duration after which artifact will expire in days.
        retention-days: 1
